### ISSUE TITLE
Remove OpenSAML dependency

### ISSUE THREAD

**Issue by serac** [Jasig/java-cas-client#100]
Summary of proposal discussed, and more or less agreed upon, on mailing list [1]:

Our needs for OpenSAML aren't worth the headaches it causes by pulling in a fairly large set of dependencies. The meager SAML parsing capability it provides can be replaced by a straightforward XPath implementation.

[1] https://groups.google.com/forum/#!topic/jasig-cas-dev/_yFr4-UUTIw

**Comment by battags** [comment]
I thought we had an issue for this already? (I apparently have a poor memory).  I've got some outstanding changes to move the SAML code into its own module too. May not be worth it if we do this.

**Comment by serac** [comment]
I looked before creating and didn't see anything. Feel free to close if this is a dupe. In any case I hope to have this done by tomorrow, so hopefully that saves you some effort. :)

**Comment by serac** [comment]
Pull request with candidate fix: #101.

**Comment by serac** [comment]
I believe I've addressed all feedback. Clear to merge & close? I'm eager to get this in and move forward with a 3.4 release.

**Comment by leleuj** [comment]
+1

**Comment by battags** [comment]
+1.  My only outstanding question (because I don't have the source code checked out on this machine) is whether the JodaTime stuff can all be moved to the SAML module just to reduce the dependencies we pull in for core (i.e. people who don't use SAML)

**Comment by serac** [comment]
It's required to be in core due to usage in `CommonUtils`:

https://github.com/Jasig/java-cas-client/blob/no-opensaml/cas-client-core/src/main/java/org/jasig/cas/client/util/CommonUtils.java#L36

**Comment by battags** [comment]
It looks like its formatting and parsing UTC:
https://github.com/Jasig/java-cas-client/blob/no-opensaml/cas-client-core/src/main/java/org/jasig/cas/client/util/CommonUtils.java#L73

I didn't think we were using that anywhere other than SAML, were we?

**Comment by serac** [comment]
That's correct. They seemed general enough to leave in CommonUtils, which is where they were previously, but I'll move into a separate utility class if you have concerns.

**Comment by battags** [comment]
Only concerned because it requires core to pull in JodaTime.  If you can move them into the SAML module along with the JodaTime dependency, my +1 remains (i.e. make the change and just merge).  Does that sound okay?

**Comment by serac** [comment]
Works for me, thanks.

**Comment by serac** [comment]
I plan to merge tomorrow as agreed.

**Comment by serac** [comment]
#101 merged as discussed.
