### ISSUE TITLE
SAML Validator does not parse out TARGET

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#104]
The response that is sent to the CAS client when a SAML request comes in, both includes TARGET and SAMLArt. When the client receives this response and attempts to call samlValidate, it does not parse out TARGET, which means the TARGET parameter that is passed will include itself!

Apparently, this has always been the behavior of both the server and the client. I only noticed it because validation started to fail for me since CAS has started to enforce validation rules for the TARGET parameter. 

One possibility would be to also remove TARGET from the service url that is constructed. Since it's not removed, it's considered as a normal query string parameter which will cause validation to fail since original TARGET will not match new TARGET.

**Comment by battags** [comment]
@mmoayyed do you want to fix this before we cut 3.4?

**Comment by mmoayyed** [comment]
I sure would like to. I did make a few changes to CAS so this problem is not apparent anymore, but it would good for the client to also sanitize the parameter. Give me a day and I should have a PR by tomorrow morning for you review.
