### ISSUE TITLE
Move the client documentation from the Jasig wiki

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#107]
The wiki is outdated and is far behind on the set of settings that the client can do. A more natural spot for the client config might be the project wiki.

**Comment by mmoayyed** [comment]
@battags you are OK with this issue? I have some time that I can dedicate to writing docs.

**Comment by battags** [comment]
Sure -- whatever is easiest for us to maintain and keep up to date!

**Comment by mmoayyed** [comment]
This is now done https://github.com/Jasig/java-cas-client/blob/master/README.md
