### ISSUE TITLE
DISABLE_XML_SCHEMA_VALIDATION key is not used anywhere

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#108]
Title says all. Should be used or removed. Probably has some use in the saml module.

**Comment by battags** [comment]
It should be deprecated/ignored most likely if we're changing it in a minor release.

**Comment by serac** [comment]
+1 to get rid of it, though I guess @battags is right that deprecation before removal is more polite. The only use case I'm aware of is in the SAML module as you said.
