### ISSUE TITLE
CAS in Portal Websphere 8.5

### ISSUE THREAD

**Issue by sergiokus** [Jasig/java-cas-client#110]
Hello,

I am trying to integrate CAS and Websphere Portal 8.5. I have read a lot about this topic, TAI...

I desire to configure properly this redirection:

See attached picture.
![caswas](https://cloud.githubusercontent.com/assets/12730241/7958967/dbf7c1a8-09f4-11e5-85f2-b3d350c9dfbb.jpg)

I have deployed in my WAS libraries:
- CasClientWebsphere-x.x.x.jar\ and casclient-2.1.1.jar into <WPSInstallDirectory>/AppServer/lib/ext

Also, I have created the interceptor. I have followed these instructions: https://wiki.jasig.org/pages/viewpage.action?pageId=19314

I would like to authenticate the portal with CAS instead of the regular user/passw.

Could you help me??

Thanks in advance.

Best Regards,

Sergio

**Comment by serac** [comment]
Questions ought to be directed to the mailing lists:

http://jasig.github.io/cas/Mailing-Lists.html
