### ISSUE TITLE
Validation filters do not provide gateway support

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#118]
I might be missing something obvious here, but as much as I can tell, there is no way to specify gateway=true on a validator.

**Comment by battags** [comment]
On a validator or a validator filter?

You wouldn't need it for the validator itself since that value is not passed to the backend.  Typically, "gateway" is handled by the AuthenticationFilter because its part of the authentication flow.

**Comment by mmoayyed** [comment]
You are right. never mind.
