### ISSUE TITLE
Deploy SNAPSHOTs to Sonatype

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#119]
Figure out what it would take to publish snapshots to sonatype on a per-commit basis.

**Comment by mmoayyed** [comment]
@leleuj does this interest you? I think you have done this a number of times for pac4j.

**Comment by leleuj** [comment]
Yes, I'll do that.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/java-cas-client/pull/122

**Comment by mmoayyed** [comment]
I realized Travis wasn't actually activated for the project. Did that just now.
