### ISSUE TITLE
Update to Java 6 or 7?

### ISSUE THREAD

**Issue by leleuj** [Jasig/java-cas-client#121]

**Comment by leleuj** [comment]
@battags : what do you think about upgrading to Java 6 at least?

**Comment by battags** [comment]
In terms of what? Using Java 6 features?  Or just updating the target?  I see no value in updating the target unless we have a compelling feature use case.

**Comment by leleuj** [comment]
I don't see really interesting features for us in Java 6, it's more about following the general Java ecosystem upgrade movment. Java 7 would provide some syntaxic sugars: diamond operator, switch case for String, try/catch resource...

**Comment by battags** [comment]
I'm not against upgrading if there is something that makes life easier for us.  I just try to balance us getting some syntactic sugar versus reducing the pool of people who can upgrade to the latest version.

**Comment by battags** [comment]
That said, since I think even Java 7 has been deprecated, it might be time to go to at least Java 6 :-)

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/java-cas-client/pull/124

**Comment by mmoayyed** [comment]
Could I propose that we go to Java 8 for the next minor release? This is the perfect use case #127 
Base64 decoding is already provided by Java 8.

**Comment by mmoayyed** [comment]
Or maybe the next next minor release :)

**Comment by battags** [comment]
We can't break compatibility in a minor release unfortunately.  I'd actually be curious though as to what JVM most people are on to set that as our new minimum.

**Comment by battags** [comment]
If we want to get rid of Commons Codec it looks like we'll need to go to at least Java 1.6.  I think that's fine.  I'd hesitate to go higher than 1.7 right now without a compelling reason.  Though we flagged this for 3.5 and the Codec issue for 4.0.  We should pick one version and do them both :-)

**Comment by mmoayyed** [comment]
Switching to java 1.6 for 3.5 makes sense to me. I do have a few other smaller proposals that would be good candidates for 3.5 so would rather not do 4.0 immediately. 

We may also want to consider upgrading the servlet api version. Having the client auto register itself in the web context is useful feature that would only be possible with the new api.
