### ISSUE TITLE
Remove commons-codec as a core dependency

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#127]
It is marked as optional yes, but I would feel better if we removed it. There is only one method in that entire lib we need, and that hasnt changed in a very long time. Best to minimize dependencies.

**Comment by battags** [comment]
Do you know if we can just switch to this?
http://www.adam-bien.com/roller/abien/entry/base64_encoding_with_jdk_1

If so, we'd probably have to bump to JDK6 but I think at this point its pretty safe to do that :-)

**Comment by battags** [comment]
I just tried it and all the tests pass still.
