### ISSUE TITLE
java-cas-client 3.4.0 is unable to inject a custom ConfigurationStrategy

### ISSUE THREAD

**Issue by juanpablo-santos** [Jasig/java-cas-client#131]
`ConfigurationStrategyName.resolveToConfigurationStrategy(configurationStrategyName)` is used to locate the class which will be used to instantiate the appropiate `ConfigurationStrategy`.

`ConfigurationStrategyName.resolveToConfigurationStrategy(configurationStrategyName)` reads as follows (added inline comments):

```java
public static Class<? extends ConfigurationStrategy> resolveToConfigurationStrategy(final String value) {
    if (CommonUtils.isBlank(value)) { // no value provided, return default
        return DEFAULT.configurationStrategyClass;
    }

    for (final ConfigurationStrategyName csn : values()) { // check for in-built strategies
        if (csn.name().equalsIgnoreCase(value)) {
            return csn.configurationStrategyClass;
        }
    }

    try { // check if it is a custom strategy
        final Class<?> clazz = Class.forName(value);

        if (clazz.isAssignableFrom(ConfigurationStrategy.class)) { // -- BUG here
            return (Class<? extends ConfigurationStrategy>) clazz;
        }
    }   catch (final ClassNotFoundException e) {
        LOGGER.error("Unable to locate strategy {} by name or class name.  Using default strategy instead.", value, e);
    }
    // always returns default...
    return DEFAULT.configurationStrategyClass;
}
```

Specifically, when indicating a custom ConfigurationStrategy the following bit is executed (lines 62-67):
```java
try {
    final Class<?> clazz = Class.forName(value);

    if (clazz.isAssignableFrom(ConfigurationStrategy.class)) { // <-- ALWAYS EVALUATES TO FALSE
        return (Class<? extends ConfigurationStrategy>) clazz;
    }
```

that `if` never yields `true`, as it should be set the other way round:
```java
try {
    final Class<?> clazz = Class.forName(value);

    if (ConfigurationStrategy.class.isAssignableFrom(clazz)) {
        return (Class<? extends ConfigurationStrategy>) clazz;
    }
```

f.ex., `org.jasig.cas.client.configuration.PropertiesConfigurationStrategyImpl.class.isAssignableFrom(ConfigurationStrategy.class)` is always `false`, whereas `ConfigurationStrategy.class.isAssignableFrom(org.jasig.cas.client.configuration.PropertiesConfigurationStrategyImpl.class)` is always `true`. So, providing a custom strategy results in returning the default strategy.

Any chances to release this quick fix as 3.4.1? We're mantaining a parallel class structure in order to be able to inject our configuration with 3.3.3, and being able to inject a custom ConfigurationStrategy would be a huge time-saver for us.

**Comment by battags** [comment]
Yes -- I was planning on cutting 3.4.1 this weekend so I'll get this in (with a test to make sure we don't accidentally reverse that logic again)

**Comment by serac** [comment]
+1

**Comment by mmoayyed** [comment]
Closed via https://github.com/Jasig/java-cas-client/issues/133
