### ISSUE TITLE
create the "service" parameter depending on the X-Forwarded-Host header

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#134]
Just in case anybody stumbles upon this in the archives:
I solved my problem by removing the "final" statement from AbstractCasFilter's
constructServiceUrl() and then subclassed it for use as "CAS Validation Filter"
in web.xml. Inside that overwritten method I now can check the X-Forwarded-Host
HTTP header and then adjust the service URL.

best regards

-christian-

-----------------------------------------------------------------------

Hello

One of my applications is reachable und different domain names like
"www.foo.de", "www.bar.de" etc. which are configured as Apache 
ServerName/ServerAlias. The requests are then proxies to a Glassfish 
server which runs one single myapp.war file with a JSF application 
that uses CAS authentication.

I planned to use the X-Forwarded-Host header to tell which domain was
originally requested and depending on this change some CSS stylings.

After adding CAS though, I ran into the problem that I have to supply a
"cas/service" or "cas/serverName" JNDI variable which is then used by
AuthenticationFilter and Cas20ProxyReceivingTicketValidationFilter to 
create this service= URL parameter. If that service parameter always
contains the same values though, my clients are always redirected back
to the same domain name :-(

What could I do to make the "service" parameter depending on the
X-Forwarded-Host header?

(I already tried to add a filter init param "authenticationRedirectStrategyClass"
which modifies the redirect URL. The validation filter always sends the same 
hostname though which is why the CAS server does not find the Service Ticket
and rejects the request.)

**Comment by battags** [comment]
The serverName param should actually take multiple values and we'd use (separated via space) if the host name matches one of those then we'll use it. See this method:
https://github.com/Jasig/java-cas-client/blob/master/cas-client-core/src/main/java/org/jasig/cas/client/util/CommonUtils.java#L228
