### ISSUE TITLE
Doc description about the "casServerUrlPrefix" property  of SingleSignOutFilter is inconsistent.

### ISSUE THREAD

**Issue by lizhe2004** [Jasig/java-cas-client#135]
in the segment "**Configuring Single Sign Out**",  the property "**casServerUrlPrefix**" of **SingleSignOutFilter** is "**required**" in the table, but there is no such property exist in the xml configuration 
```
<filter>
   <filter-name>CAS Single Sign Out Filter</filter-name>
   <filter-class>org.jasig.cas.client.session.SingleSignOutFilter</filter-class>
</filter>
```

And in the segment "**Client Configuration Using Spring**" , the doc mentions "As the **SingleSignOutFilter**, HttpServletRequestWrapperFilter and AssertionThreadLocalFilter have **no** configuration options, we recommend you just configure them in the web.xml"

because the property "**casServerUrlPrefix**"  is required, so I think we should not say "have no **no** configuration options".   

shall we should refine the doc description ?

**Comment by leleuj** [comment]
Thanks for reporting. Feel free to submit a pull request to fix the documentation.

**Comment by mmoayyed** [comment]
https://github.com/Jasig/java-cas-client/commit/8d6c6e375840956461bba08f28dfddc89a5a9f37
