### ISSUE TITLE
Produce a changelog for 3.4.x

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/java-cas-client#159]
It would be very helpful if we could document the changes that have gone into 3.4.x and do it for every release.

I can try to prepare one, similar to what we do for CAS under Github releases. Would that be acceptable?

**Comment by serac** [comment]
Anything is better than what we have now, which is nothing. A changelog would be very useful to me as a deployer. +1 for what you proposed.

**Comment by mmoayyed** [comment]
Done https://github.com/Jasig/java-cas-client/releases

Went as far as 3.3.x

**Comment by mmoayyed** [comment]
For future reference, here is the command I ran:

```
github-changes -o Jasig -r java-cas-client -k OAUTH_TOKEN --use-commit-body --only-pulls -n TAG_NAME
```

**Comment by leleuj** [comment]
+1
